name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm i --unsafe-perm && pnpm preload && cd android && chmod +x gradlew && ./gradlew assembleDebug --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: android/app/build/outputs/apk/debug/app-debug.apk